FROM node:18-alpine3.16 as base

RUN apk update && apk upgrade && \
    rm -rf /var/cache/apk/* && mkdir -p /usr/src/app

RUN chown -R node:node /usr/src/app
WORKDIR /usr/src/app
COPY --chown=node:node package*.json ./
USER node
RUN npm i

FROM base as prod
WORKDIR /usr/src/app
USER node
ENV NODE_ENV=prod
COPY --chown=node:node --from=base /usr/src/app/node_modules ./node_modules
COPY --chown=node:node ["./*.js", "package*.json", "prod.env", "./"]
EXPOSE 8080
CMD ["npm", "run", "prod"]
