name: NodeJS Checks and PR validation

on:
  push:
    branches: [ "master", "stage", "dev"]

jobs:
  docker-build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        stage: [ {env: dev, port: 3000}, {env: stage, port: 3010}, {env: prod, port: 8000} ]
    env:
      NODE_ENV: ${{ matrix.stage.env }}
      PORT: ${{ matrix.stage.port }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        env:
          VERSION: v1.0.0-${{ matrix.stage.env }}
        with:
          images: aade/node
          labels: |
            maintainer=Ade
            org.opencontainers.image.title=Nodejsdemo
            org.opencontainers.image.description=Nodejs Demo
            org.opencontainers.image.vendor=360ace
          tags: |
            type=ref,event=branch
            type=raw,value=v1.0.0-${{ matrix.stage.env }}
            type=sha

      - name: Replace Env Values
        uses: franzbischoff/replace_envs@v1
        env:
          VERSION: v1.0.0-${{ matrix.stage.env }}
          PORT: ${{ matrix.stage.port }}
          NODE_ENV: ${{ matrix.stage.env }}
        with:
          from_file: env-template
          to_file: .env
          commit: 'false'

      - name: Replace Dockerfile Env
        uses: franzbischoff/replace_envs@v1
        env:
          PORT: ${{ matrix.stage.port }}
          NODE_ENV: ${{ matrix.stage.env }}
        with:
          from_file: Dockerfile
          to_file: Dockerfile
          commit: 'false'

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: false
          # push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          # tags: aade/node:v1.0.0-${{ matrix.stage.env }}
          labels: ${{ steps.meta.outputs.labels }}